package com.eteks.sweethome3d.plugin.wallsocket;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import com.eteks.sweethome3d.model.Content;
import com.eteks.sweethome3d.model.HomePieceOfFurniture;
import com.eteks.sweethome3d.tools.URLContent;

/**
 * Assembles a wall socket from its parts (frame + inserts) into a single OBJ/MTL
 * model. All dimensions are in centimetres. Each gang is a 55x55 mm aperture that
 * holds one full-width insert or two half-width inserts side by side.
 */
public final class SocketModel {
  private SocketModel() {
  }

  private static final float GANG = 5.5f;        // 55 mm gang aperture
  private static final float MARGIN = 1.3f;      // frame border around the gangs
  private static final float FRAME_DEPTH = 0.6f;
  private static final float CORNER_R = 0.8f;
  private static final float INSERT_THICKNESS = 0.3f;

  /** One insert placed in a gang: a type plus whether it is half width. */
  public static final class Insert {
    public final InsertType type;
    public final boolean half;

    public Insert(InsertType type, boolean half) {
      this.type = type;
      this.half = half;
    }
  }

  /** Configuration of the socket: finishes, standard and one insert list per gang. */
  public static final class Config {
    public Finish frameFinish = Finish.WHITE;
    public Finish insertFinish = Finish.WHITE;
    public Standard standard = Standard.SCHUKO;
    public final List<List<Insert>> gangs = new ArrayList<List<Insert>>();
  }

  /** Result of composition: full OBJ text, MTL text and Sweet Home 3D dimensions. */
  public static final class Result {
    public final String obj;
    public final String mtl;
    public final float width;
    public final float depth;
    public final float height;
    public final String name;

    Result(String obj, String mtl, float width, float depth, float height, String name) {
      this.obj = obj;
      this.mtl = mtl;
      this.width = width;
      this.depth = depth;
      this.height = height;
      this.name = name;
    }
  }

  public static Result compose(Config config, InsertCatalog catalog) {
    Finish frame = config.frameFinish;
    Finish insert = config.insertFinish;

    MaterialPalette palette = new MaterialPalette();
    palette.add("Frame", frame.r, frame.g, frame.b);
    palette.add("Insert", insert.r, insert.g, insert.b);
    palette.add("Rocker", insert.r * 0.82f, insert.g * 0.82f, insert.b * 0.82f);
    palette.add("Hole", 0.05f, 0.05f, 0.05f);
    palette.add("Metal", 0.72f, 0.73f, 0.75f);

    int n = config.gangs.size();
    float frameW = n * GANG + 2 * MARGIN;
    float frameH = GANG + 2 * MARGIN;

    List<ObjMerger.Placement> placements = new ArrayList<ObjMerger.Placement>();
    placements.add(new ObjMerger.Placement(buildFrame(frameW, frameH), 0, 0, 0));

    float maxFeature = 0;
    for (int i = 0; i < n; i++) {
      float gangX = (i - (n - 1) / 2f) * GANG;
      List<Insert> inserts = config.gangs.get(i);
      float totalWidth = 0;
      for (Insert in : inserts) {
        totalWidth += in.half ? 0.5f : 1f;
      }
      float cursor = gangX - totalWidth * GANG / 2f;
      for (Insert in : inserts) {
        float w = in.half ? GANG / 2f : GANG;
        ModelPart part = catalog.resolve(in.type, in.half, config.standard);
        if (part == null) {
          part = buildInsert(in.type, in.half, config.standard);
        }
        placements.add(new ObjMerger.Placement(part, cursor + w / 2f, 0, FRAME_DEPTH / 2f));
        cursor += w;
        maxFeature = Math.max(maxFeature, featureDepth(in.type));
      }
    }

    String body = ObjMerger.merge(placements);
    String obj = "# generated by WallSocketPlugin\nmtllib socket.mtl\n" + body;
    return new Result(obj, palette.toMtl(), frameW, FRAME_DEPTH + maxFeature, frameH, "Wall socket");
  }

  /** Human-readable name summarising the configuration (e.g. "Wall socket — 2 gangs"). */
  public static String name(Config config) {
    StringBuilder sb = new StringBuilder("Wall socket");
    if (config.gangs.isEmpty()) {
      return sb.toString();
    }
    if (config.gangs.size() == 1) {
      sb.append(" — ").append(insertsLabel(config.gangs.get(0)));
    } else {
      sb.append(" — ").append(config.gangs.size()).append(" gangs");
    }
    return sb.toString();
  }

  /**
   * Stores the configuration on the piece as first-class properties, so it persists
   * in the home and can be read back (and exported) via
   * {@code HomePieceOfFurniture#getProperty} / {@code getPropertyNames}.
   */
  public static void applyMetadata(HomePieceOfFurniture piece, Config config) {
    piece.setProperty("wallsocket.type", "wall-socket");
    piece.setProperty("wallsocket.standard", config.standard.name());
    piece.setProperty("wallsocket.frameFinish", config.frameFinish.name());
    piece.setProperty("wallsocket.insertFinish", config.insertFinish.name());
    piece.setProperty("wallsocket.gangCount", String.valueOf(config.gangs.size()));
    for (int i = 0; i < config.gangs.size(); i++) {
      piece.setProperty("wallsocket.gang." + (i + 1), gangLabel(config.gangs.get(i)));
    }
  }

  private static String gangLabel(List<Insert> inserts) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < inserts.size(); i++) {
      if (i > 0) {
        sb.append('+');
      }
      Insert in = inserts.get(i);
      sb.append(in.type.name());
      if (in.half) {
        sb.append("_H");
      }
    }
    return sb.toString();
  }

  private static String insertsLabel(List<Insert> inserts) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < inserts.size(); i++) {
      if (i > 0) {
        sb.append(" + ");
      }
      Insert in = inserts.get(i);
      sb.append(in.type.name().toLowerCase(Locale.ROOT));
      if (in.half) {
        sb.append(" (half)");
      }
    }
    return sb.toString();
  }

  private static ModelPart buildFrame(float w, float h) {
    ObjWriter o = new ObjWriter();
    o.useMaterial("Frame");
    o.roundedRectPrism(0, 0, 0, w, h, FRAME_DEPTH, CORNER_R, 8);
    return new ModelPart(o.objBody());
  }

  private static ModelPart buildInsert(InsertType type, boolean half, Standard standard) {
    ObjWriter o = new ObjWriter();
    float w = half ? GANG / 2f : GANG;
    float h = GANG;
    o.useMaterial("Insert");
    o.roundedRectPrism(0, 0, INSERT_THICKNESS / 2f, w, h, INSERT_THICKNESS, 0.4f, 6);
    switch (type) {
      case SOCKET:
        renderSocket(o, half, standard);
        break;
      case ROCKER: {
        float rw = half ? 1.6f : 2.6f;
        o.useMaterial("Rocker");
        o.roundedRectPrism(0, 0, 0.4f, rw, 4.6f, 0.2f, 0.5f, 6);
        break;
      }
      case USB: {
        float pw = half ? 0.9f : 1.0f;
        o.useMaterial("Hole");
        o.roundedRectPrism(0, 0, 0.31f, pw, 1.4f, 0.05f, 0.1f, 4);
        break;
      }
      case RJ45: {
        float s = half ? 1.0f : 1.1f;
        o.useMaterial("Hole");
        o.roundedRectPrism(0, 0, 0.31f, s, s, 0.05f, 0.1f, 4);
        break;
      }
      case DIMMER: {
        float knobR = half ? 0.9f : 1.3f;
        o.useMaterial("Rocker");
        o.cylinderZ(0, 0, 0.45f, knobR, 0.3f, 32);
        o.useMaterial("Hole");
        o.disc(0, 0, 0.61f, knobR * 0.25f, 20);
        break;
      }
      case BLANK:
        break;
    }
    return new ModelPart(o.objBody());
  }

  private static void renderSocket(ObjWriter o, boolean half, Standard standard) {
    switch (standard) {
      case UK: {
        float faceW = half ? 2.6f : 4.6f;
        float faceH = half ? 4.8f : 4.6f;
        float slotL = half ? 0.8f : 1.8f;   // horizontal slot length
        float slotT = half ? 0.45f : 0.6f;  // slot thickness
        float slotX = half ? 0.55f : 0.85f;
        float slotY = 0.9f;
        float earthL = half ? 1.2f : 1.8f;
        o.useMaterial("Insert");
        o.roundedRectPrism(0, 0, 0.35f, faceW, faceH, 0.1f, 0.3f, 6);
        o.useMaterial("Hole");
        // live (left) and neutral (right): horizontal slots
        o.roundedRectPrism(-slotX, slotY, 0.42f, slotL, slotT, 0.05f, 0.1f, 4);
        o.roundedRectPrism(slotX, slotY, 0.42f, slotL, slotT, 0.05f, 0.1f, 4);
        // earth (bottom center): vertical slot
        o.roundedRectPrism(0, -slotY, 0.42f, slotT, earthL, 0.05f, 0.1f, 4);
        break;
      }
      case GENERIC: {
        // simple round two-pin socket, no ground contacts
        o.useMaterial("Insert");
        o.cylinderZ(0, 0, 0.4f, half ? 1.2f : 2.25f, 0.2f, 32);
        o.useMaterial("Hole");
        if (half) {
          o.disc(0, 0.45f, 0.51f, 0.24f, 24);
          o.disc(0, -0.45f, 0.51f, 0.24f, 24);
        } else {
          o.disc(0.95f, 0, 0.51f, 0.24f, 24);
          o.disc(-0.95f, 0, 0.51f, 0.24f, 24);
        }
        break;
      }
      case SCHUKO:
      default: {
        o.useMaterial("Insert");
        if (half) {
          // narrow socket: vertical pins, ground clips left/right
          o.cylinderZ(0, 0, 0.4f, 1.2f, 0.2f, 32);
          o.useMaterial("Hole");
          o.disc(0, 0.45f, 0.51f, 0.24f, 24);
          o.disc(0, -0.45f, 0.51f, 0.24f, 24);
          o.useMaterial("Metal");
          o.box(1.2f, 0, 0.4f, 0.15f, 1.0f, 0.2f);
          o.box(-1.2f, 0, 0.4f, 0.15f, 1.0f, 0.2f);
        } else {
          // full socket: horizontal pins, ground clips top/bottom
          o.cylinderZ(0, 0, 0.4f, 2.25f, 0.2f, 32);
          o.useMaterial("Hole");
          o.disc(0.95f, 0, 0.51f, 0.24f, 24);
          o.disc(-0.95f, 0, 0.51f, 0.24f, 24);
          o.useMaterial("Metal");
          o.box(0, 2.1f, 0.4f, 1.6f, 0.15f, 0.2f);
          o.box(0, -2.1f, 0.4f, 1.6f, 0.15f, 0.2f);
        }
        break;
      }
    }
  }

  /** Front-most local Z of the insert's features (used to size the piece depth). */
  private static float featureDepth(InsertType type) {
    switch (type) {
      case SOCKET: return 0.51f;
      case ROCKER: return 0.5f;
      case USB: return 0.34f;
      case RJ45: return 0.34f;
      case DIMMER: return 0.61f;
      case BLANK: default: return INSERT_THICKNESS;
    }
  }

  /** Writes the OBJ and MTL to a fresh temporary directory and returns the OBJ content. */
  public static Content saveToTemp(String obj, String mtl) throws IOException {
    File dir = Files.createTempDirectory("wallsocket").toFile();
    File objFile = new File(dir, "socket.obj");
    File mtlFile = new File(dir, "socket.mtl");
    try (PrintWriter out = new PrintWriter(
        Files.newBufferedWriter(objFile.toPath(), StandardCharsets.UTF_8))) {
      out.print(obj);
    }
    try (PrintWriter out = new PrintWriter(
        Files.newBufferedWriter(mtlFile.toPath(), StandardCharsets.UTF_8))) {
      out.print(mtl);
    }
    return new URLContent(objFile.toURI().toURL());
  }

  /** Deletes the temporary OBJ/MTL files behind a content previously created by {@link #saveToTemp}. */
  public static void deleteContent(Content content) {
    if (content instanceof URLContent) {
      try {
        File objFile = new File(((URLContent) content).getURL().toURI());
        objFile.delete();
        File dir = objFile.getParentFile();
        File mtlFile = new File(dir, "socket.mtl");
        if (mtlFile.exists()) {
          mtlFile.delete();
        }
        if (dir != null && dir.isDirectory()) {
          dir.delete();
        }
      } catch (Exception ignored) {
        // ignore: cleanup is best-effort
      }
    }
  }
}
